package rise.lib.utils.i8n;

public enum StringCodes {
	ERROR_API_ORG_ALREADY_EXISTS,
	ERROR_API_USERID_ALREADY_EXISTS,
	ERROR_API_MISSING_ACCEPT_TERMS_AND_PRIVACY,
	ERROR_API_WRONG_USER_OR_PASSWORD,
	
	WARNING_API_PASSWORD_EXPIRED,
	
	NOTIFICATIONS_ADMIN_CONFIRM_MAIL_TITLE,
	NOTIFICATIONS_ADMIN_CONFIRM_MAIL_MESSAGE
}
