package rise.lib.utils.i8n;

public enum StringCodes {
	ERROR_API_ORG_ALREADY_EXISTS,
	ERROR_API_USERID_ALREADY_EXISTS,
	ERROR_API_MAIL_ALREADY_EXISTS,
	ERROR_API_MISSING_ACCEPT_TERMS_AND_PRIVACY,
	ERROR_API_WRONG_USER_OR_PASSWORD,
	ERROR_API_WRONG_OTP,
	ERROR_API_USER_ALREADY_EXISTS,
	ERROR_API_CONFIRM_EXPIRED,
	
	WARNING_API_PASSWORD_EXPIRED,
	
	NOTIFICATIONS_ADMIN_CONFIRM_MAIL_TITLE,
	NOTIFICATIONS_ADMIN_CONFIRM_MAIL_MESSAGE,
	NOTIFICATIONS_INVITE_MAIL_TITLE,
	NOTIFICATIONS_INVITE_MAIL_MESSAGE,
	NOTIFICATIONS_USR_CONFIRMED_MAIL_TOADMIN_TITLE,
	NOTIFICATIONS_USR_CONFIRMED_MAIL_TOADMIN_MESSAGE,	
	
	OTP_TITLE,
	OTP_MESSAGE,
	
	PLUGIN_FLOOD,
	PLUGIN_DROUGHT,
	PLUGIN_BUILDINGS,
	PLUGIN_IMPACTS
	
}
